spring:
 profiles:
   active:
   - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: servicecloud-config-xiaohe-dev 
---
spring:
  profiles: test  #开发环境
  application:
    name: servicecloud-config-xiaohe-test
 #utf-8保存