spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001 # 注册中心占用的7001端口。冒号后面必须要有空格号
  
spring:
  profiles: dev
  application:
    name: servicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka7001.com 
  client: 
    register-with-eureka: false   #当前自己注册自己进服务中
    fetch-registry: false  #不同过eureka获取注册信息
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001 # 注册中心占用的7001端口。冒号后面必须要有空格号
  
spring:
  profiles: test
  application:
    name: servicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka7001.com 
  client: 
    register-with-eureka: false   #当前自己注册自己进服务中
    fetch-registry: false  #不同过eureka获取注册信息
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  